project:
  type: book
  output-dir: docs

book:
  title: "Module 6: Introduction to Data Processing & Programming in R"
  repo-url: https://github.com/gerkovink/sur
  repo-branch: book
  repo-actions: [edit, issue]
  author:
  - name: Gerko Vink
    orcid: 0000-0001-9767-1924
    email: g.vink@uu.nl
  date: last-modified
  chapters:
    - index.qmd
    - overview.qmd
    - team.qmd
    - deliverables.qmd
    - genai.qmd
    - meeting1.qmd
    - meeting2.qmd
    - meeting3.qmd
    - meeting4.qmd
    - meeting5.qmd
    - meeting6.qmd
    - meeting7.qmd
    - meeting8.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



